# --- !Ups

create table "product" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "color" varchar not null,
  "size" varchar not null,
);

create table "product_quantity" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "productId" bigint not null,
  "quantity" NUMBER not null,
   foreign key ("productId") references "product"("id")
);

create table "order" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" number not null,
  "date" varchar not null,
);

create table "order_product" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "productId" bigint not null,
  "orderId" bigint not null,
  "orderQuantity" number not null,
);

insert into "product" ("color", "size") values ('czerwony', 'S');
insert into "product" ("color", "size") values ('czerwony', 'M');
insert into "product" ("color", "size") values ('czerwony', 'L');
insert into "product" ("color", "size") values ('czerwony', 'XL');
insert into "product" ("color", "size") values ('zielony', 'S');
insert into "product" ("color", "size") values ('zielony', 'M');
insert into "product" ("color", "size") values ('zielony', 'L');
insert into "product" ("color", "size") values ('zielony', 'XL');
insert into "product" ("color", "size") values ('niebieski', 'S');
insert into "product" ("color", "size") values ('niebieski', 'M');
insert into "product" ("color", "size") values ('niebieski', 'L');
insert into "product" ("color", "size") values ('niebieski', 'XL');


insert into "product_quantity" ("productId", "quantity") values (1, 0);
insert into "product_quantity" ("productId", "quantity") values (2, 2);
insert into "product_quantity" ("productId", "quantity") values (3, 5);
insert into "product_quantity" ("productId", "quantity") values (4, 3);

insert into "product_quantity" ("productId", "quantity") values (5, 2);
insert into "product_quantity" ("productId", "quantity") values (6, 4);
insert into "product_quantity" ("productId", "quantity") values (7, 1);
insert into "product_quantity" ("productId", "quantity") values (8, 6);

insert into "product_quantity" ("productId", "quantity") values (9, 3);
insert into "product_quantity" ("productId", "quantity") values (10, 4);
insert into "product_quantity" ("productId", "quantity") values (11, 0);
insert into "product_quantity" ("productId", "quantity") values (12, 3);
insert into "product_quantity" ("productId", "quantity") values (12, 3);

# --- !Downs

drop table "people" if exists;